### ISSUE TITLE
🗻 Epic: Store management

### ISSUE THREAD

**Issue by oryanmoshe** [oryanmoshe/escargot#4]
**Describe the solution you'd like**
Allow users to configure connections to new stores / select existing connections to explore.
This issue refers to the TUI purely, without logic implementations.

**Tasks**
- [ ] Store management logic (#7)
- [ ] Initialization check (#5)
- [ ] Credentials insertion page (#6)
- [ ] Store selection page (#8)
- [ ] Store list management (#9)
